version: "3"
services:
  web:
   depends_on: 
   - database 
   image: php72:pdo
   container_name: php72
   ports:
   - 8080:80
  
  database:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
      MYSQL_USER: Lwalid
      MYSQL_PASSWORD: testmdp
    ports:
    - 6633:3306
    volumes:
    - myapp:/var/lib/mysql

  phpmyadmin:
    depends_on: 
    - database  
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=database


volumes:
  myapp:
